export const MESSAGE_LOADED = 'MESSAGE_LOADED';
export const LOAD_MESSAGE = 'LOAD_MESSAGE';
export const PUBLISH_MESSAGE = 'PUBLISH_MESSAGE';
export const MESSAGE_PUBLISHED = 'MESSAGE_PUBLISHED';
export const MESSAGE_NOT_FOUND = 'MESSAGE_NOT_FOUND';

export const LOAD_HISTORY = 'LOAD_HISTORY';
export const HISTORY_LOADED =  'HISTORY_LOADED';
export const SAVE_HISTORY = 'SAVE_HISTORY';
export const HISTORY_SAVED = 'HISTORY_SAVED';

export const LOAD_TOP = 'LOAD_TOP';
export const TOP_LOADED = 'TOP_LOADED';

export const NOTIFICATION = 'NOTIFICATION';
export const RESET_NOTIFICATION = 'RESET_NOTIFICATION';

export const SET_ALGORITHM = 'SET_ALGORITHM';

export const LOG_IN = 'LOG_IN';
export const LOG_OUT = 'LOG_OUT';

export const LOAD_AUTHORED = 'LOAD_AUTHORED';
export const AUTHORED_LOADED = 'AUTHORED_LOADED';

export const MESSAGE_READ_EVENT = 'MESSAGE_READ_EVENT';
