export const MESSAGE_LOADED = 'MESSAGE_LOADED';
export const LOAD_MESSAGE = 'LOAD_MESSAGE';
export const PUBLISH_MESSAGE = 'PUBLISH_MESSAGE';
export const MESSAGE_PUBLISHED = 'MESSAGE_PUBLISHED';

export const SET_VIEW = 'SET_VIEW';

export const LOAD_HISTORY = 'LOAD_HISTORY';
export const HISTORY_LOADED =  'HISTORY_LOADED';
export const SAVE_HISTORY = 'SAVE_HISTORY';
export const HISTORY_SAVED = 'HISTORY_SAVED';
