export const READER_VIEW = 'READER_VIEW';
export const INTERACTOR_VIEW = 'INTERACTOR_VIEW';
export const HISTORY_VIEW = 'HISTORY_VIEW';
export const EXPLORER_VIEW = 'EXPLORER_VIEW';
export const AUTHOR_VIEW = 'AUTHOR_VIEW';